### ISSUE TITLE
ephem.Observer().lon hanging on certain inputs with python3

### ISSUE THREAD

**Issue by mweisman** [brandon-rhodes/pyephem#207]
Certain float values are hanging indefinitely and using 100% CPU when being set as the longitude in an Observer in python3.

Simple reproduction case:
```
import ephem
observer = ephem.Observer()
observer.lon = "-113.78401934344532"
```

I have reproduced this on Ubuntu 16.04 with pyephem 3.7.6.0 and python 3.5.2 as well as on Mac OS 11.2 with pyephem 3.7.7.1 and python 3.8.2. The same Ubuntu environment does not have this issue with python 2.7.12. I may be able to get a few more values that cause this issue if needed.

**Comment by brandon-rhodes** [comment]
Well — tarnation! I can confirm that your simple script hangs forever. As I have time over the rest of the week, I'll dig in with debuggers at the C level and let you know what I learn.

**Comment by drbitboy** [comment]
https://github.com/brandon-rhodes/pyephem/blob/9328b03fde2c390b86e396a292fb3eb39d7cbaae/extensions/dtoa.c#L2955

?

**Comment by brandon-rhodes** [comment]
> `for(;;) {`

That’s the C version of Python’s `while True:`, where the condition for leaving the loop is a `break` or `return` inside. (Was that your question? Feel free to elaborate.)

**Comment by brandon-rhodes** [comment]
The underlying problem, for everyone following along, seems to be that the underlying `libastro` code expects base-60 fractions like `23:45:67`, not decimal fractions with a decimal point, and instead of giving a clean error it simply hangs if presented with a period in the middle of the number it's trying to parse. I'm looking at replacing the old C parsing code with something simpler.

**Comment by brandon-rhodes** [comment]
Why do both `parse_angle()` and `to_angle()` exist? They do exactly the same thing, but in slightly incompatibly different ways, and have swapped return values, but otherwise look identical. Present-day Brandon is a bit miffed with 2004-Brandon, after whom he must now clean up. :)

**Comment by drbitboy** [comment]
My (implied) question was whether that was the loop that was not terminating.

I just looked again and realized I missed the -- prefix on the j in the first [if] expression; without that -- the loop could enter a state where it does not terminate.

So never mind.

**Comment by brandon-rhodes** [comment]
I've completely rewritten sexagesimal parsing, in the hopes of:

* accepting float values in each of the fields `whole:minutes:seconds`
* never entering an infinite loop
* and avoiding all of the local-sensitivity incurred by raw C calls.

We'll see what CI thinks of my "improved" code.

**Comment by brandon-rhodes** [comment]
I've released version 4.0.0 with this fix. Let me know if you have any further problems, and thanks for reporting the bug!

**Comment by ludwigschwardt** [comment]
Wow, a new major release :-D

In case you missed it, space separators used to work and now doesn't. In other words, this worked before:
```Python
print(ephem.degrees('12 34 56'))
# 12:34:56.0
```
Some databases like SIMBAD like this style for some reason.

**Comment by brandon-rhodes** [comment]
Interesting! I wasn't aware that format was accepted by the library. I'll look this afternoon to see if there's a quick way it could be restored.

**Comment by drbitboy** [comment]
suggestion:
```
import re
rgx_hms = re.compile('^ *(\d+)([: ](\d+)([: ](\d+([.]\d+)*))*)*')
```
Example:
```
def degrees(hms_string='12 24:56.789'):  ### to show either separator will work
    match = rgx_hms.match(hms_string)
    if None is match: return None
    groups = match.groups()
    L = len(groups)
    hours,minutes,seconds = map(float,([groups[0], L > 2 and groups[2] or '0', L > 4 and groups[4] or '0']+['0','0'])[:3])
    return (hours * 15.0) + (minutes / 4.0) + (seconds / 240.0)
```
Obviously there needs to be range checks, etc.

Wait, are we coding this is in C?  Hmm, maybe this?
```
sscanf(input_string,"%d[: ]%d[: ]%lf",&int_hours,&int_minutes,&double_seconds);
```

**Comment by brandon-rhodes** [comment]
1. Alas, `sscanf()` isn't possible because it switches from wanting `.` to `,` for the decimal separator depending on whether the machine's locale settings are, say, the US or Germany.
2. We also need to allow floats for the whole and minutes parts, as the example that lead off this issue is purely a decimal number without any `:` sexagesimal delimiters at all.

I might try to import the `re` module in the C code and building an RE to do the splitting. I'll probably use `r'\w+|\w*:\w*'` and call the RE object’s `.split()` method.

**Comment by drbitboy** [comment]
sscanf(string,"[^ :][ :]...',...,string_hours,...)?

**Comment by brandon-rhodes** [comment]
I wasn't able to find a good path through with scanf — not only was the code complicated enough that I worried about being able to maintain it, but I wasn't able to handle the edge cases in a way that satisfied me. (I think `1::2` is one degree 2 arcseconds, for example?) But if you get something working I'd be interested in looking at it; for as quick a fix as possible for this new use case, though, I'm likely to use a Python RE as that will fit the existing code well.

**Comment by ludwigschwardt** [comment]
Releasing a new major version is a good way to make the users come out of the woodwork 😂 

> Interesting! I wasn't aware that format was accepted by the library. I'll look this afternoon to see if there's a quick way it could be restored.

This is perhaps a testament to the opacity of the previous parser... 😄 
We fixed the few catalogue entries we had, but I reckon someone out there might be relying on it.

**Comment by drbitboy** [comment]
I am going to try to make scansexa a wrapper that calls the existing scansexa as scansexa_sep, but with a with a separator.  If there is success with colon (_sep returns 0), good, use that.  if not (_sep returns -1), then try with NULL (equivalent to whitespace separator).

**Comment by brandon-rhodes** [comment]
That's an interesting approach, but I think it probably fails with something like this: `12 34:56`. Which I think is something the pre-4.0 routine supported, and so we should probably continue to support?

**Comment by drbitboy** [comment]
Yah good point.

**Comment by brandon-rhodes** [comment]
@ludwigschwardt — Thanks again for pointing out that unexpected but possibly-in-use edge case in the old parser! And your “opacity of the previous parser” comment gave me a good laugh.

I've committed a fix, along with 6 new test strings that pretty thoroughly exercise the new behavior:

```
        self.assertAlmostEqual(self.d, degrees('85 56 37'),
                               places=arcsecond_places)
        self.assertAlmostEqual(self.d, degrees('85 56:37'),
                               places=arcsecond_places)
        self.assertAlmostEqual(self.d, degrees('85:56 37'),
                               places=arcsecond_places)
        self.assertAlmostEqual(self.d, degrees('85 : 56 : 37'),
                               places=arcsecond_places)
        self.assertAlmostEqual(self.d, degrees(' 85 : 56 : 37 '),
                               places=arcsecond_places)
        self.assertAlmostEqual(self.d, degrees(' :  :   309397    '),
                               places=arcsecond_places)
```

Once the CI system lights up green, I'll make a new release, hopefully by the end of the day!

**Comment by ludwigschwardt** [comment]
Thanks as always, Brandon! Yeah, I had a history with the parser, dating back to #5 :joy:

**Comment by brandon-rhodes** [comment]
> Yeah, I had a history with the parser, dating back to #5 

Oh, wow, no wonder your name looked familiar! Your comment now has the full context for me that it lacked. :) Thanks for your long-term interest in the project!

**Comment by brandon-rhodes** [comment]
The new version is out! Let me know if there are any further parsing problems, and thanks again for letting me know quickly, hopefully before any more users were affected.

**Comment by drbitboy** [comment]
Sidebar:  not really a problem; perhaps the .degrees function, or anything else that calls scansexa, could pre-check and run interference:
```
>>> ephem.degrees('1:1:1')
0.01774902886542011
>>> ephem.degrees('1:1:1:0')
0.01774902886542011
>>> ephem.degrees('1:1:1')-ephem.degrees('1:1:1:0')
0.0
>>> ephem.degrees('1:1:1:1e6')
0.09855130905034279
```

**Comment by brandon-rhodes** [comment]
Which exception? And what kind of pre-check are you thinking of? I'm not able to guess from your example code (but I haven't had coffee yet).

**Comment by drbitboy** [comment]
>Which exception?

By analogy to the exception for 1:2:bar in ephem/tests/test_angles.py, I would expect 1:1:1:1 to cause an exception somewhere in either ephem.degrees or its callees

>what kind of pre-check

do a check pre-scansexa i.e. between ephem.degrees inclusive and scansexa exclusive, because scansexa only is doing its thing i.e. evaluating a polynomial with coefficients = ([60]*(n-1))+[1]

**Comment by brandon-rhodes** [comment]
The problem with `1:2:bar` is that `bar` isn't a number. But just as decimals can go to 3 digits behind the decimal place `1.123`, so I think it's allowed for sexagesimal numbers to have 3 "digits" beyond the whole number `1:1:2:3`? While astronomers tend to stick to minutes and second-minutes, I don't think there's a problem with supporting third-minutes? (Or fourth-minutes, or however many colons folks want to append.)

**Comment by drbitboy** [comment]
I am not saying **_scansexa_** should be limited in the number of sexadecimal digits it parses.  No, it is good that it is general.  I am saying rather that that _**ephem.degrees**_ should throw the exception if it gets more than three, if for no other reason than that there is no convention to define if the digits are super-degrees:degrees:arcminutes:arcseconds or degrees:arcminutes:arcseconds:sub-arcseconds; of course only the latter has the faint but non-zero chance of making numerical sense, but that is not for the code to decide.

**Comment by brandon-rhodes** [comment]
The convention that additional fields specify additional base-60 fraction is, I believe, a long tradition in astronomy. For example, take a look at page 2 of:

http://www.pitt.edu/~brg/pdfs/brg_i_1.pdf

While academic historians do make the clarifying step of using `;` for the “sexagesimal point” and `,` to separate the components behind the point, you can see several Babylonian measures given which go to a 3rd and even a 4th base-60 “digit”. While XEphem does make the simplification of flattening out symbols, turning the rich variety of `°` and `′` and `″` into the plain and somewhat ambiguous — but easy to type! — character `:`, and thus loses the helpful variety of a different symbol for the whole and fraction, I think the convention of base-60 is well enough established that we shouldn't make the code more complicated to warn people away from as much base-60 as they would like.

I'll be happy to revisit in the future if users report problems with strings like `1:2:3:4`, but let’s wait for those cases to arise so we can be certain what they look like.

**Comment by drbitboy** [comment]
Cool, thanks.
